### ISSUE TITLE
GET account paginator, filter and sort

### ISSUE THREAD

**Issue by javigs82** [accentation/resource-server#6]
Build a REST API service:

GET /account paginator, sort and filter by  id

**Comment by raflazpel** [comment]
Edited: "Sorted and filtered by Id"

**Comment by javigs82** [comment]
need to be filtered by officeId

**Comment by raflazpel** [comment]
Already fixed.

**Comment by javigs82** [comment]
Add account paginator per clients

**Comment by aochoa017** [comment]
done
